# Generated by Django 3.2 on 2023-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='heading',
            field=models.CharField(default=1, help_text='Введите заголовок обзора', max_length=256, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
