# Generated by Django 3.2 on 2023-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20230317_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.FloatField(null=True, verbose_name='Рейтинг'),
        ),
    ]
